### ISSUE TITLE
List of suggestions

### ISSUE THREAD

**Issue by MLNW** [Kkoile/skess#7] opened 2020-11-21 15:04 UTC
Yesterday, we played your game for a few hours and had a lot of fun. During the session, a few things kept coming up that could be improved upon to make this game even better:

* While sketching
  * Add color bucket to be able to fill in shapes with selected color
  * Allow more colors
  * Yellow is very bright
  * There doesn't seem to be a nice brownish color
  * Lines sketched in the last few seconds of a round are often not part of the submitted sketch
* While guessing
  * It would be great to see who else is still guessing and who is already done
* Postgame summary
  * Some of the text is overlaid onto the sketch which sometimes hides key features of the drawing
  * When scrolling through the various sketches
    * It would be great to see the original word but also the last guessed word
    * The UI often says it is still loading a sketch even though it is already displayed
    * When moving forward to see the guessed word for a certain sketch it actually loads the image again
    * When going back and forth images that were already loaded have to be loaded again
    * Maybe a GIF or an animation of some kind would be cool
* Other
  * It is possible to "cheat" by reloading the page which erases everything that was drawn so far and resets the timer
  * If this happens it would be nice to be able to turn in your drawing once you are done since others may have to wait for you
  * Some kind of scoring system would make this game more enjoyable for the more competitive crowd out there 😄 

@Agreon might be able to help with some of these 😉

**Comment by Kkoile** [comment] 2020-11-22 16:21
Thanks very much for helping to improve Skess! It's always great to hear that people are playing this game and have fun with it!
I will try to apply your feedback as soon as possible. As it is an open source repository, you're more than welcome to also help me by opening a pull request.

> Add color bucket to be able to fill in shapes with selected color

Unfortunately, the library I'm using doesn't offer this feature. But perhaps we can open an issue to them https://github.com/tbolis/react-sketch/

Regarding the postgame summary. I know, that the screen is not ideal at all. When I try to add the information it always looks to packed. Perhaps you can come up with a design mockup and then I try to implement it.

> It is possible to "cheat" by reloading the page which erases everything that was drawn so far and resets the timer

This is intended behaviour ;-) Because people might have a slow internet connection, it is the mitigation for that. Otherwise it could be that the server rejects an image, just because it was sent in a few milliseconds too late.

> Some kind of scoring system would make this game more enjoyable for the more competitive crowd out there 😄

I would also love that, but didn't come up with a good idea. Perhaps you have an idea?

**Comment by Kkoile** [comment] 2020-11-29 15:39
I deployed a new version with the following changes:
 - yellow is now not so bright anymore
 - brown looks more like brown
 - included a color picker, so you can choose your own colors
 - if you still draw, while the time is up, I simulate a `mouseup` event, so that the stroke will still be recognized

I will close this issue and open multiple smaller ones for the missing parts. 

Have fun testing the new features and playing!

**Closed by Kkoile** 2020-11-29 15:39 UTC
